### ISSUE TITLE
Error: Could not find or load main class .

### ISSUE THREAD

**Issue by jackcviers** [luben/sctags#5]
scala 2.12.3 is on my path

```
$ which scala
/c/Program Files (x86)/scala/bin/scala
```

When I run 

```
$ sctags -R ./
```

from inside a scala project, I get

```
$ sctags -R ./
Error: Could not find or load main class .
```

**Comment by luben** [comment]
Addressed it the last commit. The problem was the spaces in the path to scala. It should handle them correctly now.
